name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run build with Gradle(check styles, run tests)
        run: ./gradlew build

      - name: Build the tagged Docker image
        run: docker build -f .docker/testHeroku.Dockerfile -t testheroku .

      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
        with:
        email: ${{ secrets.HEROKU_EMAIL }}
        api_key: ${{ secrets.HEROKU_API_KEY }}
        docker_compose_file: '.docker/docker-compose.yml'
        heroku_apps: '[{"imagename":"testheroku","appname":"dokaztest","apptype":"web"}]'
