name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print test
        run: echo Hello from test
    
  build:
    runs-on: ubuntu-latest
    needs: [test]
    
    steps:
    - name: Print build
      run: echo Hello from build
