name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run build with Gradle(check styles, run tests)
        run: ./gradlew build
        
      - name: Deploy Docker Image to Heroku App
        uses: jctaveras/heroku-deploy@v2.1.1
        with:
          # Email Linked to your Heroku Account
          email: ${{ secrets.HEROKU_EMAIL }}
          # Heroku Dyno Formation
          formation: web
          # Your Heroku API Key
          api_key: ${{ secrets.HEROKU_API_KEY }}
          # Your Heroku App Name
          app_name: dokaztest
          # Dokerfile path
          dockerfile_path: ".docker/testHeroku.Dockerfile"
