name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: minddocdev/mou-version-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prefix: mygroup/