name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kyoh86/git-vertag-action@v1
        with:
          method: minor  # "major", "minor", "patch" or "get"
        id: vertag
      - run: echo ${{ steps.vertag.outputs.vertag }}