name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: tag-version
        uses: juliansangillo/tag-version@v1.5
        with:
          production-branch: master
          test-branch: test
          dev-branch: develop