name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Github Tag Bump and `latest` tag update
        uses: WiktorJ/github-tag-action@2.0.0