name: Bump version
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Quill Git Semantic Version
        uses: kahuang/semantic-version@v4.3